### ISSUE TITLE
 failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan 

### ISSUE THREAD

**Issue by grekpg** [saibotk/pterodactyl-panel-docker#1]
pterodactyl-panel-docker$ docker exec -it pterodactyl-panel-docker_php_1 upgrade
Rerunning script as webserver user.
!!! PLEASE BACKUP ANY IMPORTANT DATA BEFORE UPGRADING !!!
Are you sure you want to continue the upgrade script? (Y/n)
YRunning upgrade script.

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18
Removing cached configuration.
rm: can't remove 'bootstrap/cache/*': No such file or directory
Rerunning configuration scripts.

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18
Removing cached views.

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18
Running migrations.

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18
Cleaning up API keys.

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18
Upgrade complete. Please restart the container to load changes.

Warning: require(/var/www/html/pterodactyl/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/pterodactyl/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/pterodactyl/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/pterodactyl/artisan on line 18

**Comment by saibotk** [comment]
This project is not maintained anymore sorry
